[[funnels]]
funnel_id = "user_onboarding"
label = "User Onboarding Funnel"

[[funnels.steps]]
name = "Signup"
metric_id = "metric_1"

[[funnels.steps]]
name = "Activation"
metric_id = "some_other_metric"